name: pick_cup
args: []
kwargs: {}

dataset:
  _target_: "datasets.pick_cup_dset.load_pick_cup_slice_train_val"
  n_rollout: null
  normalize_action: ${normalize_action}
  data_path: ${oc.env:DATASET_DIR}/pick_cup
  split_ratio: 0.9
  transform:
    _target_: "datasets.img_transforms.default_transform"
    img_size: ${img_size}

decoder_path: null
num_workers: 16